// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ecar.proto

package com.smartcityDS;

public interface chargingDurationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chargingDuration)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string chargingDuration = 1;</code>
   */
  java.lang.String getChargingDuration();
  /**
   * <code>string chargingDuration = 1;</code>
   */
  com.google.protobuf.ByteString
      getChargingDurationBytes();
}
