// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ecar.proto

package grpcSmartCity.ecar;

public interface pluginAvailabilityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcSmartCity.pluginAvailability)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pluginAvailability = 1;</code>
   */
  java.lang.String getPluginAvailability();
  /**
   * <code>string pluginAvailability = 1;</code>
   */
  com.google.protobuf.ByteString
      getPluginAvailabilityBytes();
}
