// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ecar.proto

package grpcSmartCity.ecar;

public interface pluginAmountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcSmartCity.pluginAmount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pluginAmount = 1;</code>
   */
  java.lang.String getPluginAmount();
  /**
   * <code>string pluginAmount = 1;</code>
   */
  com.google.protobuf.ByteString
      getPluginAmountBytes();
}
