// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ecar.proto

package grpcSmartCity.ecar;

public interface pluginDeleteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcSmartCity.pluginDelete)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pluginDelete = 1;</code>
   */
  java.lang.String getPluginDelete();
  /**
   * <code>string pluginDelete = 1;</code>
   */
  com.google.protobuf.ByteString
      getPluginDeleteBytes();
}
