// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ecar.proto

package grpcSmartCity.ecar;

public interface pluginSpecificOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcSmartCity.pluginSpecific)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pluginSpecific = 1;</code>
   */
  java.lang.String getPluginSpecific();
  /**
   * <code>string pluginSpecific = 1;</code>
   */
  com.google.protobuf.ByteString
      getPluginSpecificBytes();
}
