// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ecar.proto

package com.smartcityDS;

public interface preciseLocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:preciseLocation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string preciseLocation = 1;</code>
   */
  java.lang.String getPreciseLocation();
  /**
   * <code>string preciseLocation = 1;</code>
   */
  com.google.protobuf.ByteString
      getPreciseLocationBytes();
}
