// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: escooter.proto

package smartcityds.escooter;

public interface scooterSpecificOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartcityds.scooterSpecific)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string scooterSpecific = 1;</code>
   */
  java.lang.String getScooterSpecific();
  /**
   * <code>string scooterSpecific = 1;</code>
   */
  com.google.protobuf.ByteString
      getScooterSpecificBytes();
}
