// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: escooter.proto

package smartcityds.escooter;

public interface scooterAvailabilityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartcityds.scooterAvailability)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string scooterAvailability = 1;</code>
   */
  java.lang.String getScooterAvailability();
  /**
   * <code>string scooterAvailability = 1;</code>
   */
  com.google.protobuf.ByteString
      getScooterAvailabilityBytes();
}
