// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ebus.proto

package com.smartcityDS;

public interface busNumberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:busNumber)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string busNumber = 1;</code>
   */
  java.lang.String getBusNumber();
  /**
   * <code>string busNumber = 1;</code>
   */
  com.google.protobuf.ByteString
      getBusNumberBytes();
}
