// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: escooter.proto

package com.smartcityDS;

public interface numberAvailableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:numberAvailable)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string numberAvailable = 1;</code>
   */
  java.lang.String getNumberAvailable();
  /**
   * <code>string numberAvailable = 1;</code>
   */
  com.google.protobuf.ByteString
      getNumberAvailableBytes();
}
