// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ebus.proto

package grpcSmartCity.ebus;

/**
 * Protobuf type {@code grpcSmartCity.busTimetable}
 */
public  final class busTimetable extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpcSmartCity.busTimetable)
    busTimetableOrBuilder {
private static final long serialVersionUID = 0L;
  // Use busTimetable.newBuilder() to construct.
  private busTimetable(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private busTimetable() {
    busTimetable_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private busTimetable(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            busTimetable_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpcSmartCity.ebus.smartcityDSServiceImpl.internal_static_grpcSmartCity_busTimetable_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpcSmartCity.ebus.smartcityDSServiceImpl.internal_static_grpcSmartCity_busTimetable_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpcSmartCity.ebus.busTimetable.class, grpcSmartCity.ebus.busTimetable.Builder.class);
  }

  public static final int BUSTIMETABLE_FIELD_NUMBER = 1;
  private volatile java.lang.Object busTimetable_;
  /**
   * <code>string busTimetable = 1;</code>
   */
  public java.lang.String getBusTimetable() {
    java.lang.Object ref = busTimetable_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      busTimetable_ = s;
      return s;
    }
  }
  /**
   * <code>string busTimetable = 1;</code>
   */
  public com.google.protobuf.ByteString
      getBusTimetableBytes() {
    java.lang.Object ref = busTimetable_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      busTimetable_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getBusTimetableBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, busTimetable_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getBusTimetableBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, busTimetable_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpcSmartCity.ebus.busTimetable)) {
      return super.equals(obj);
    }
    grpcSmartCity.ebus.busTimetable other = (grpcSmartCity.ebus.busTimetable) obj;

    boolean result = true;
    result = result && getBusTimetable()
        .equals(other.getBusTimetable());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BUSTIMETABLE_FIELD_NUMBER;
    hash = (53 * hash) + getBusTimetable().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpcSmartCity.ebus.busTimetable parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpcSmartCity.ebus.busTimetable parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpcSmartCity.ebus.busTimetable parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpcSmartCity.ebus.busTimetable parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpcSmartCity.ebus.busTimetable parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpcSmartCity.ebus.busTimetable parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpcSmartCity.ebus.busTimetable parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpcSmartCity.ebus.busTimetable parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpcSmartCity.ebus.busTimetable parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpcSmartCity.ebus.busTimetable parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpcSmartCity.ebus.busTimetable parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpcSmartCity.ebus.busTimetable parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpcSmartCity.ebus.busTimetable prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpcSmartCity.busTimetable}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpcSmartCity.busTimetable)
      grpcSmartCity.ebus.busTimetableOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpcSmartCity.ebus.smartcityDSServiceImpl.internal_static_grpcSmartCity_busTimetable_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpcSmartCity.ebus.smartcityDSServiceImpl.internal_static_grpcSmartCity_busTimetable_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpcSmartCity.ebus.busTimetable.class, grpcSmartCity.ebus.busTimetable.Builder.class);
    }

    // Construct using grpcSmartCity.ebus.busTimetable.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      busTimetable_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpcSmartCity.ebus.smartcityDSServiceImpl.internal_static_grpcSmartCity_busTimetable_descriptor;
    }

    @java.lang.Override
    public grpcSmartCity.ebus.busTimetable getDefaultInstanceForType() {
      return grpcSmartCity.ebus.busTimetable.getDefaultInstance();
    }

    @java.lang.Override
    public grpcSmartCity.ebus.busTimetable build() {
      grpcSmartCity.ebus.busTimetable result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpcSmartCity.ebus.busTimetable buildPartial() {
      grpcSmartCity.ebus.busTimetable result = new grpcSmartCity.ebus.busTimetable(this);
      result.busTimetable_ = busTimetable_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpcSmartCity.ebus.busTimetable) {
        return mergeFrom((grpcSmartCity.ebus.busTimetable)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpcSmartCity.ebus.busTimetable other) {
      if (other == grpcSmartCity.ebus.busTimetable.getDefaultInstance()) return this;
      if (!other.getBusTimetable().isEmpty()) {
        busTimetable_ = other.busTimetable_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpcSmartCity.ebus.busTimetable parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpcSmartCity.ebus.busTimetable) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object busTimetable_ = "";
    /**
     * <code>string busTimetable = 1;</code>
     */
    public java.lang.String getBusTimetable() {
      java.lang.Object ref = busTimetable_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        busTimetable_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string busTimetable = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBusTimetableBytes() {
      java.lang.Object ref = busTimetable_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        busTimetable_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string busTimetable = 1;</code>
     */
    public Builder setBusTimetable(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      busTimetable_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string busTimetable = 1;</code>
     */
    public Builder clearBusTimetable() {
      
      busTimetable_ = getDefaultInstance().getBusTimetable();
      onChanged();
      return this;
    }
    /**
     * <code>string busTimetable = 1;</code>
     */
    public Builder setBusTimetableBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      busTimetable_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpcSmartCity.busTimetable)
  }

  // @@protoc_insertion_point(class_scope:grpcSmartCity.busTimetable)
  private static final grpcSmartCity.ebus.busTimetable DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpcSmartCity.ebus.busTimetable();
  }

  public static grpcSmartCity.ebus.busTimetable getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<busTimetable>
      PARSER = new com.google.protobuf.AbstractParser<busTimetable>() {
    @java.lang.Override
    public busTimetable parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new busTimetable(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<busTimetable> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<busTimetable> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpcSmartCity.ebus.busTimetable getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

