// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ecar.proto

package smartcityds.ecar;

public interface pluginAmountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartcityds.pluginAmount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pluginAmount = 1;</code>
   */
  java.lang.String getPluginAmount();
  /**
   * <code>string pluginAmount = 1;</code>
   */
  com.google.protobuf.ByteString
      getPluginAmountBytes();
}
