// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: escooter.proto

package com.smartcityDS;

public interface rentalCostOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rentalCost)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string rentalCost = 1;</code>
   */
  java.lang.String getRentalCost();
  /**
   * <code>string rentalCost = 1;</code>
   */
  com.google.protobuf.ByteString
      getRentalCostBytes();
}
