// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ebus.proto

package smartcityds.ebus;

public interface busNumberofSeatsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartcityds.busNumberofSeats)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string busNumberofSeats = 1;</code>
   */
  java.lang.String getBusNumberofSeats();
  /**
   * <code>string busNumberofSeats = 1;</code>
   */
  com.google.protobuf.ByteString
      getBusNumberofSeatsBytes();
}
