// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ebus.proto

package smartcityds.ebus;

public interface busSpecificOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartcityds.busSpecific)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string busSpecific = 1;</code>
   */
  java.lang.String getBusSpecific();
  /**
   * <code>string busSpecific = 1;</code>
   */
  com.google.protobuf.ByteString
      getBusSpecificBytes();
}
