// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ebus.proto

package smartcityds.ebus;

public final class smartcityDSServiceImpl {
  private smartcityDSServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartcityds_busNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartcityds_busNumber_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartcityds_busTimetable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartcityds_busTimetable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartcityds_busNumberofSeats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartcityds_busNumberofSeats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartcityds_busNumberofUsb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartcityds_busNumberofUsb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartcityds_busSpecific_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartcityds_busSpecific_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartcityds_busAmount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartcityds_busAmount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartcityds_busDelete_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartcityds_busDelete_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nebus.proto\022\013smartcityds\"\036\n\tbusNumber\022\021" +
      "\n\tbusNumber\030\001 \001(\t\"$\n\014busTimetable\022\024\n\014bus" +
      "Timetable\030\001 \001(\t\",\n\020busNumberofSeats\022\030\n\020b" +
      "usNumberofSeats\030\001 \001(\t\"(\n\016busNumberofUsb\022" +
      "\026\n\016busNumberofUsb\030\001 \001(\t\"\"\n\013busSpecific\022\023" +
      "\n\013busSpecific\030\001 \001(\t\"\036\n\tbusAmount\022\021\n\tbusA" +
      "mount\030\001 \001(\t\"\036\n\tbusDelete\022\021\n\tbusDelete\030\001 " +
      "\001(\t2\333\002\n\013smartcityDS\022A\n\014getTimetable\022\026.sm" +
      "artcityds.busNumber\032\031.smartcityds.busTim" +
      "etable\022I\n\020getNumberofSeats\022\026.smartcityds" +
      ".busNumber\032\035.smartcityds.busNumberofSeat" +
      "s\022E\n\016getNumberofUsb\022\026.smartcityds.busNum" +
      "ber\032\033.smartcityds.busNumberofUsb\022:\n\006seeB" +
      "us\022\030.smartcityds.busSpecific\032\026.smartcity" +
      "ds.busAmount\022;\n\tdeleteBus\022\026.smartcityds." +
      "busNumber\032\026.smartcityds.busDeleteB,\n\020sma" +
      "rtcityds.ebusB\026smartcityDSServiceImplP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartcityds_busNumber_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartcityds_busNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartcityds_busNumber_descriptor,
        new java.lang.String[] { "BusNumber", });
    internal_static_smartcityds_busTimetable_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartcityds_busTimetable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartcityds_busTimetable_descriptor,
        new java.lang.String[] { "BusTimetable", });
    internal_static_smartcityds_busNumberofSeats_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smartcityds_busNumberofSeats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartcityds_busNumberofSeats_descriptor,
        new java.lang.String[] { "BusNumberofSeats", });
    internal_static_smartcityds_busNumberofUsb_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smartcityds_busNumberofUsb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartcityds_busNumberofUsb_descriptor,
        new java.lang.String[] { "BusNumberofUsb", });
    internal_static_smartcityds_busSpecific_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_smartcityds_busSpecific_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartcityds_busSpecific_descriptor,
        new java.lang.String[] { "BusSpecific", });
    internal_static_smartcityds_busAmount_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_smartcityds_busAmount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartcityds_busAmount_descriptor,
        new java.lang.String[] { "BusAmount", });
    internal_static_smartcityds_busDelete_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_smartcityds_busDelete_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartcityds_busDelete_descriptor,
        new java.lang.String[] { "BusDelete", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
