// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ebus.proto

package com.smartcityDS;

public interface busstopLocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:busstopLocation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string busstopLocation = 1;</code>
   */
  java.lang.String getBusstopLocation();
  /**
   * <code>string busstopLocation = 1;</code>
   */
  com.google.protobuf.ByteString
      getBusstopLocationBytes();
}
