// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ecar.proto

package com.smartcityDS;

public interface cityNameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cityName)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cityName = 1;</code>
   */
  java.lang.String getCityName();
  /**
   * <code>string cityName = 1;</code>
   */
  com.google.protobuf.ByteString
      getCityNameBytes();
}
