// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: escooter.proto

package com.smartcityDS;

public final class Escooter {
  private Escooter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_locationPrecise_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_locationPrecise_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rentalCost_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rentalCost_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_numberAvailable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_numberAvailable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rentalDuration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rentalDuration_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016escooter.proto\"*\n\017locationPrecise\022\027\n\017l" +
      "ocationPrecise\030\001 \001(\t\" \n\nrentalCost\022\022\n\nre" +
      "ntalCost\030\001 \001(\t\"*\n\017numberAvailable\022\027\n\017num" +
      "berAvailable\030\001 \001(\t\"(\n\016rentalDuration\022\026\n\016" +
      "rentalDuration\030\001 \001(\t2\261\001\n\020electricscooter" +
      "s\0225\n\017getAvailability\022\020.locationPrecise\032\020" +
      ".numberAvailable\022.\n\rgetRentalCost\022\020.loca" +
      "tionPrecise\032\013.rentalCost\0226\n\021getRentalDur" +
      "ation\022\020.locationPrecise\032\017.rentalDuration" +
      "B\023\n\017com.smartcityDSP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_locationPrecise_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_locationPrecise_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_locationPrecise_descriptor,
        new java.lang.String[] { "LocationPrecise", });
    internal_static_rentalCost_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rentalCost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rentalCost_descriptor,
        new java.lang.String[] { "RentalCost", });
    internal_static_numberAvailable_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_numberAvailable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_numberAvailable_descriptor,
        new java.lang.String[] { "NumberAvailable", });
    internal_static_rentalDuration_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_rentalDuration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rentalDuration_descriptor,
        new java.lang.String[] { "RentalDuration", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
