// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ebus.proto

package com.smartcityDS;

public interface numberofSeatsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:numberofSeats)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string numberofSeats = 1;</code>
   */
  java.lang.String getNumberofSeats();
  /**
   * <code>string numberofSeats = 1;</code>
   */
  com.google.protobuf.ByteString
      getNumberofSeatsBytes();
}
