// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ebus.proto

package com.smartcityDS;

public interface TimetableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Timetable)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Timetable = 1;</code>
   */
  java.lang.String getTimetable();
  /**
   * <code>string Timetable = 1;</code>
   */
  com.google.protobuf.ByteString
      getTimetableBytes();
}
