// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ebus.proto

package com.smartcityDS;

public interface usbPortsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:usbPorts)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string usbPorts = 1;</code>
   */
  java.lang.String getUsbPorts();
  /**
   * <code>string usbPorts = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsbPortsBytes();
}
