// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: escooter.proto

package com.smartcityDS;

public interface locationPreciseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:locationPrecise)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string locationPrecise = 1;</code>
   */
  java.lang.String getLocationPrecise();
  /**
   * <code>string locationPrecise = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationPreciseBytes();
}
