// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ebus.proto

package grpcSmartCity.ebus;

public interface busNumberofUsbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcSmartCity.busNumberofUsb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string busNumberofUsb = 1;</code>
   */
  java.lang.String getBusNumberofUsb();
  /**
   * <code>string busNumberofUsb = 1;</code>
   */
  com.google.protobuf.ByteString
      getBusNumberofUsbBytes();
}
