// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: escooter.proto

package grpcSmartCity.escooter;

public interface rentalDurationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcSmartCity.rentalDuration)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string rentalDuration = 1;</code>
   */
  java.lang.String getRentalDuration();
  /**
   * <code>string rentalDuration = 1;</code>
   */
  com.google.protobuf.ByteString
      getRentalDurationBytes();
}
