// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: escooter.proto

package grpcSmartCity.escooter;

public interface scooterDeleteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcSmartCity.scooterDelete)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string scooterDelete = 1;</code>
   */
  java.lang.String getScooterDelete();
  /**
   * <code>string scooterDelete = 1;</code>
   */
  com.google.protobuf.ByteString
      getScooterDeleteBytes();
}
