// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: escooter.proto

package grpcSmartCity.escooter;

public interface scooterAmountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcSmartCity.scooterAmount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string scooterAmount = 1;</code>
   */
  java.lang.String getScooterAmount();
  /**
   * <code>string scooterAmount = 1;</code>
   */
  com.google.protobuf.ByteString
      getScooterAmountBytes();
}
