// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: escooter.proto

package grpcSmartCity.escooter;

public final class smartcityDSServiceImpl {
  private smartcityDSServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcSmartCity_scooterAvailability_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpcSmartCity_scooterAvailability_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcSmartCity_rentalCost_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpcSmartCity_rentalCost_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcSmartCity_rentalDuration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpcSmartCity_rentalDuration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcSmartCity_preciseLocation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpcSmartCity_preciseLocation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcSmartCity_scooterSpecific_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpcSmartCity_scooterSpecific_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcSmartCity_scooterAmount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpcSmartCity_scooterAmount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcSmartCity_scooterDelete_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpcSmartCity_scooterDelete_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016escooter.proto\022\rgrpcSmartCity\"2\n\023scoot" +
      "erAvailability\022\033\n\023scooterAvailability\030\001 " +
      "\001(\t\" \n\nrentalCost\022\022\n\nrentalCost\030\001 \001(\t\"(\n" +
      "\016rentalDuration\022\026\n\016rentalDuration\030\001 \001(\t\"" +
      "*\n\017preciseLocation\022\027\n\017preciseLocation\030\001 " +
      "\001(\t\"*\n\017scooterSpecific\022\027\n\017scooterSpecifi" +
      "c\030\001 \001(\t\"&\n\rscooterAmount\022\025\n\rscooterAmoun" +
      "t\030\001 \001(\t\"&\n\rscooterDelete\022\025\n\rscooterDelet" +
      "e\030\001 \001(\t2\252\003\n\013smartcityDS\022\\\n\026getScooterAva" +
      "ilability\022\036.grpcSmartCity.preciseLocatio" +
      "n\032\".grpcSmartCity.scooterAvailability\022V\n" +
      "\021getRentalDuration\022\".grpcSmartCity.scoot" +
      "erAvailability\032\035.grpcSmartCity.rentalDur" +
      "ation\022J\n\rgetRentalCost\022\036.grpcSmartCity.p" +
      "reciseLocation\032\031.grpcSmartCity.rentalCos" +
      "t\022J\n\nseeScooter\022\036.grpcSmartCity.scooterS" +
      "pecific\032\034.grpcSmartCity.scooterAmount\022M\n" +
      "\rdeleteScooter\022\036.grpcSmartCity.scooterSp" +
      "ecific\032\034.grpcSmartCity.scooterDeleteB2\n\026" +
      "grpcSmartCity.escooterB\026smartcityDSServi" +
      "ceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_grpcSmartCity_scooterAvailability_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpcSmartCity_scooterAvailability_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpcSmartCity_scooterAvailability_descriptor,
        new java.lang.String[] { "ScooterAvailability", });
    internal_static_grpcSmartCity_rentalCost_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpcSmartCity_rentalCost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpcSmartCity_rentalCost_descriptor,
        new java.lang.String[] { "RentalCost", });
    internal_static_grpcSmartCity_rentalDuration_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_grpcSmartCity_rentalDuration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpcSmartCity_rentalDuration_descriptor,
        new java.lang.String[] { "RentalDuration", });
    internal_static_grpcSmartCity_preciseLocation_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_grpcSmartCity_preciseLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpcSmartCity_preciseLocation_descriptor,
        new java.lang.String[] { "PreciseLocation", });
    internal_static_grpcSmartCity_scooterSpecific_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_grpcSmartCity_scooterSpecific_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpcSmartCity_scooterSpecific_descriptor,
        new java.lang.String[] { "ScooterSpecific", });
    internal_static_grpcSmartCity_scooterAmount_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_grpcSmartCity_scooterAmount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpcSmartCity_scooterAmount_descriptor,
        new java.lang.String[] { "ScooterAmount", });
    internal_static_grpcSmartCity_scooterDelete_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_grpcSmartCity_scooterDelete_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpcSmartCity_scooterDelete_descriptor,
        new java.lang.String[] { "ScooterDelete", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
