// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ecar.proto

package com.smartcityDS;

public interface numberofchargingPointsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:numberofchargingPoints)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string numberofchargingPoints = 1;</code>
   */
  java.lang.String getNumberofchargingPoints();
  /**
   * <code>string numberofchargingPoints = 1;</code>
   */
  com.google.protobuf.ByteString
      getNumberofchargingPointsBytes();
}
