// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ebus.proto

package com.smartcityDS;

public final class Ebus {
  private Ebus() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Timetable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Timetable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_busstopLocation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_busstopLocation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_busNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_busNumber_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_numberofSeats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_numberofSeats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_usbPorts_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_usbPorts_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nebus.proto\"\036\n\tTimetable\022\021\n\tTimetable\030\001" +
      " \001(\t\"*\n\017busstopLocation\022\027\n\017busstopLocati" +
      "on\030\001 \001(\t\"\036\n\tbusNumber\022\021\n\tbusNumber\030\001 \001(\t" +
      "\"&\n\rnumberofSeats\022\025\n\rnumberofSeats\030\001 \001(\t" +
      "\"\034\n\010usbPorts\022\020\n\010usbPorts\030\001 \001(\t2\223\001\n\004ebus\022" +
      "&\n\014getTimetable\022\n.busNumber\032\n.Timetable\022" +
      "4\n\020getNumberofSeats\022\020.busstopLocation\032\016." +
      "numberofSeats\022-\n\024getUsbPortsAvailable\022\n." +
      "busNumber\032\t.usbPortsB\023\n\017com.smartcityDSP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Timetable_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Timetable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Timetable_descriptor,
        new java.lang.String[] { "Timetable", });
    internal_static_busstopLocation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_busstopLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_busstopLocation_descriptor,
        new java.lang.String[] { "BusstopLocation", });
    internal_static_busNumber_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_busNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_busNumber_descriptor,
        new java.lang.String[] { "BusNumber", });
    internal_static_numberofSeats_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_numberofSeats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_numberofSeats_descriptor,
        new java.lang.String[] { "NumberofSeats", });
    internal_static_usbPorts_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_usbPorts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_usbPorts_descriptor,
        new java.lang.String[] { "UsbPorts", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
